apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhagyashreebanking-deploy
  labels:
    app: bhagyashree-banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bhagyashree-banking-app
  template:
    metadata:
      labels:
        app: bhagyashree-banking-app
    spec:
      containers:
      - name: bhagyashree-banking-container
        image: bhagyashreebaddoli/bhagyashreedevops:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bhagyashree-np-service
  labels:
    app: bhagyashree-banking-app
spec:
  selector:
    app: bhagyashree-banking-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8081
    targetPort: 8081
